import type { Config } from 'tailwindcss'
import typography from '@tailwindcss/typography'

/** Bảng màu / font / radius bám theo mẫu `index.html` (Material-style tokens). */
export default {
  darkMode: 'class',
  plugins: [typography],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        'on-tertiary': '#ffffff',
        'secondary-container': '#d5e3fc',
        'on-secondary-container': '#57657a',
        'inverse-surface': '#2d3133',
        'on-primary-fixed-variant': '#003ea8',
        'on-tertiary-fixed-variant': '#005049',
        'surface-container-high': '#e6e8ea',
        'surface-container': '#eceef0',
        'tertiary-fixed-dim': '#6bd8cb',
        error: '#ba1a1a',
        'surface-container-highest': '#e0e3e5',
        'error-container': '#ffdad6',
        'surface-tint': '#0053db',
        'on-secondary-fixed': '#0d1c2e',
        'outline-variant': '#c5c5d4',
        'on-surface-variant': '#454652',
        'tertiary-container': '#00665d',
        'on-tertiary-fixed': '#00201d',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        tertiary: '#004c45',
        'on-tertiary-container': '#78e4d6',
        surface: '#f7f9fb',
        'inverse-primary': '#b4c5ff',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#b9c7df',
        'tertiary-fixed': '#89f5e7',
        'on-secondary-fixed-variant': '#3a485b',
        primary: '#003aa0',
        background: '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'on-secondary': '#ffffff',
        'primary-container': '#004fd2',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-background': '#191c1e',
        'on-primary-container': '#c4d1ff',
        outline: '#757684',
        'on-primary-fixed': '#00174b',
        'surface-container-low': '#f2f4f6',
        'surface-bright': '#f7f9fb',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'on-surface': '#191c1e',
        'primary-fixed': '#dbe1ff',
        secondary: '#515f74',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        demego: '0.5rem',
      },
      typography: () => ({
        editorial: {
          css: {
            '--tw-prose-body': 'rgba(25, 28, 30, 0.9)',
            '--tw-prose-headings': '#191c1e',
            '--tw-prose-lead': '#454652',
            '--tw-prose-links': '#003aa0',
            '--tw-prose-bold': '#191c1e',
            '--tw-prose-quotes': '#454652',
            '--tw-prose-quote-borders': '#0053db',
            '--tw-prose-code': '#191c1e',
            '--tw-prose-pre-bg': '#2d3133',
            maxWidth: 'none',
            fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
            a: {
              fontWeight: '500',
              textDecoration: 'none',
              '&:hover': {
                color: '#003aa0',
                textDecoration: 'underline',
              },
            },
            h1: {
              fontFamily: 'Manrope, ui-sans-serif, system-ui, sans-serif',
              fontWeight: '800',
              letterSpacing: '-0.02em',
            },
            h2: {
              fontFamily: 'Manrope, ui-sans-serif, system-ui, sans-serif',
              fontWeight: '700',
              color: '#003aa0',
            },
            h3: {
              fontFamily: 'Manrope, ui-sans-serif, system-ui, sans-serif',
              fontWeight: '700',
            },
          },
        },
      }),
    },
  },
} satisfies Config
